//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.18 at 04:34:43 PM EET 
//


package com.shaheen.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the message package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Messages_QNAME = new QName("", "messages");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: message
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link User }
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ChatGroup }
     */
    public ChatGroup createChatGroup() {
        return new ChatGroup();
    }

    /**
     * Create an instance of {@link Style }
     */
    public Style createStyle() {
        return new Style();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "messages")
    public JAXBElement<Message> createMessages(Message value) {
        return new JAXBElement<Message>(_Messages_QNAME, Message.class, null, value);
    }

}
